# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{paperless_to_xero}
  s.version = "1.2.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Matt Patterson"]
  s.date = %q{2010-02-27}
  s.default_executable = %q{paperless_to_xero}
  s.description = %q{= Paperless-to-Xero

A simple translator which takes a CSV file from Mariner's Paperless receipt/document management software and makes a Xero accounts payable invoice CSV, for import into Xero.

Formatting in Paperless is very important, so you probably want to wait until I've written the docs}
  s.email = %q{matt@reprocessed.org}
  s.executables = ["paperless_to_xero"]
  s.extra_rdoc_files = [
    "MIT-LICENSE",
    "README.rdoc"
  ]
  s.files = Dir.glob([
    "VERSION",
    "README.rdoc",
    "MIT-LICENSE",
    "Rakefile",
    "lib/**/*.rb",
    "bin/*"
  ])
  s.homepage = %q{http://github.com/fidothe/paperless_to_xero/}
  s.rdoc_options = ["--main", "README.rdoc"]
  s.require_paths = ["lib"]
  s.rubyforge_project = %q{paperless_to_xero}
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Convert Paperless CSV exports to Xero invoice import CSV}
  s.test_files = Dir.glob([
    "spec/spec.opts",
    "spec/**/*.rb",
    "spec/fixtures/*"
  ])

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

